### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by davidnuon** [codeandcoffeelb/signup#12]
I think that @torch2424 made a good suggestion for using Google Sheets. I'm not sure if that's the best solution yet, but let's try to puzzle it out.

**Comment by davidnuon** [comment]
Google Sheets Angular Module:
https://github.com/FedericoElles/angular-google-spreadsheet

**Comment by torch2424** [comment]
@davidnuon Google sheets was just a little thing I thought up of on the spot, and @rogerhoward agreed. But I am open to anything that will allow us to store:

Name
Email
And Date

Into something that admins of the group can easily access

**Comment by torch2424** [comment]
By Suggestion, we chose stamplay https://stamplay.com/
